-- Mock physical inventory for testing BOM capacity, valuation, and low-stock status.
-- Expected result after running this file:
--   Complete DM stock: 2 DMs
--   Total valuation: Rs 33,300
--   Low-stock rows: Panel Box, 3D Print Enclosure, Tower Light, and other rows
--
-- This file removes only rows carrying this exact mock marker before inserting.
-- It does not remove real inventory or bulk-order rows.

BEGIN;

DELETE FROM public.inventory_stock
WHERE notes = 'SIMKIT_BOM_MOCK_TEST_DATA';

INSERT INTO public.inventory_stock
  (category, sensor_type, actual_quantity, min_quantity, unit_price, entry_date, notes)
VALUES
  ('PANEL BOX/DOOR/LOCK', NULL, 5, 5, 900, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('UV PRINTING', NULL, 5, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('3D PRINT ENCLOUSURE', NULL, 2, 5, 1200, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('ENCLOUSURE STICKER', NULL, 5, 5, 50, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('DIN RAIL MOUNTING CLIP', NULL, 10, 5, 25, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('LCD PCB', NULL, 5, 5, 800, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('MOTHER BOARD PCB', NULL, 5, 5, 1500, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('CAVLI PCB', NULL, 5, 5, 700, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('SIM CARD', NULL, 5, 5, 20, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('TOWER LIGHT', NULL, 2, 10, 300, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('CABLE GLAND', NULL, 15, 15, 30, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('POWER CORD CABLE', NULL, 5, 5, 200, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('MAGNETIC MOUNT ANTEENA', NULL, 4, 10, 150, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('RF CABLE (ANTEENA)', NULL, 4, 5, 80, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('ENERGY METER CT SENSOR', NULL, 0, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('ENERGY METER', NULL, 0, 5, 1000, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('YHDC CT SENSOR', NULL, 6, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('22 OHM RESISTOR FOR CT', NULL, 6, 5, 5, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('PROXIMITRY SENSOR', NULL, 5, 5, 500, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('ROTARY ENCODER', NULL, 0, 5, 500, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('VIBRATION SENSOE (VIBE Q)', NULL, 2, 5, 1000, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('4 CORE WIRE', NULL, 20, 5, 40, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('2 CORE WIRE', NULL, 30, 5, 30, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('TAPE ROLE', NULL, 0, 5, 50, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('ZIPE TIE', NULL, 0, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('BOX', NULL, 5, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA'),
  ('FORM SHEET', NULL, 0, 5, 100, CURRENT_DATE, 'SIMKIT_BOM_MOCK_TEST_DATA');

COMMIT;
