import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../../", import.meta.url));
const output = path.join(root, "supabase/dashboard-deploy");
export const attendanceFunctions = [
  "attendance-enroll-user",
  "attendance-device-event",
  "attendance-command-retry",
  "attendance-photo-access",
  "attendance-photo-cleanup",
  "attendance-leave-email",
];
await mkdir(output, { recursive: true });
const manifest = {};
for (const name of attendanceFunctions) {
  const result = await build({
    entryPoints: [path.join(root, "supabase/functions", name, "index.ts")],
    bundle: true,
    write: false,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    external: ["https://*"],
    banner: {
      js: "// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.\n// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.",
    },
  });
  const source = result.outputFiles[0].text;
  if (/from\s+["']\.\.?\//.test(source)) throw new Error(`${name} contains a local import`);
  await writeFile(path.join(output, `${name}.ts`), source);
  manifest[name] = {
    file: `${name}.ts`,
    sha256: createHash("sha256").update(source).digest("hex"),
  };
}
await writeFile(path.join(output, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(
  `Prepared ${attendanceFunctions.length} self-contained Supabase Dashboard function files.`,
);
