/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as BusinessConsultantRouteImport } from './routes/business-consultant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerTasksRouteImport } from './routes/manager.tasks'
import { Route as ManagerSitesRouteImport } from './routes/manager.sites'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerPerformanceRouteImport } from './routes/manager.performance'
import { Route as ManagerInventoryRouteImport } from './routes/manager.inventory'
import { Route as ManagerDriveLinksRouteImport } from './routes/manager.drive-links'
import { Route as ManagerBusinessConsultantsRouteImport } from './routes/manager.business-consultants'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessConsultantRoute = BusinessConsultantRouteImport.update({
  id: '/business-consultant',
  path: '/business-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSitesRoute = ManagerSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPerformanceRoute = ManagerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerInventoryRoute = ManagerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDriveLinksRoute = ManagerDriveLinksRouteImport.update({
  id: '/drive-links',
  path: '/drive-links',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBusinessConsultantsRoute =
  ManagerBusinessConsultantsRouteImport.update({
    id: '/business-consultants',
    path: '/business-consultants',
    getParentRoute: () => ManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/inventory'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/inventory'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/inventory'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BusinessConsultantRoute: typeof BusinessConsultantRoute
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-consultant': {
      id: '/business-consultant'
      path: '/business-consultant'
      fullPath: '/business-consultant'
      preLoaderRoute: typeof BusinessConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/sites': {
      id: '/manager/sites'
      path: '/sites'
      fullPath: '/manager/sites'
      preLoaderRoute: typeof ManagerSitesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/performance': {
      id: '/manager/performance'
      path: '/performance'
      fullPath: '/manager/performance'
      preLoaderRoute: typeof ManagerPerformanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/inventory': {
      id: '/manager/inventory'
      path: '/inventory'
      fullPath: '/manager/inventory'
      preLoaderRoute: typeof ManagerInventoryRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/drive-links': {
      id: '/manager/drive-links'
      path: '/drive-links'
      fullPath: '/manager/drive-links'
      preLoaderRoute: typeof ManagerDriveLinksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/business-consultants': {
      id: '/manager/business-consultants'
      path: '/business-consultants'
      fullPath: '/manager/business-consultants'
      preLoaderRoute: typeof ManagerBusinessConsultantsRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface ManagerRouteChildren {
  ManagerBusinessConsultantsRoute: typeof ManagerBusinessConsultantsRoute
  ManagerDriveLinksRoute: typeof ManagerDriveLinksRoute
  ManagerInventoryRoute: typeof ManagerInventoryRoute
  ManagerPerformanceRoute: typeof ManagerPerformanceRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSitesRoute: typeof ManagerSitesRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBusinessConsultantsRoute: ManagerBusinessConsultantsRoute,
  ManagerDriveLinksRoute: ManagerDriveLinksRoute,
  ManagerInventoryRoute: ManagerInventoryRoute,
  ManagerPerformanceRoute: ManagerPerformanceRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSitesRoute: ManagerSitesRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BusinessConsultantRoute: BusinessConsultantRoute,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
