/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as BusinessConsultantRouteImport } from './routes/business-consultant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as OwnerTasksRouteImport } from './routes/owner.tasks'
import { Route as OwnerSitesRouteImport } from './routes/owner.sites'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerReportsRouteImport } from './routes/owner.reports'
import { Route as OwnerPerformanceRouteImport } from './routes/owner.performance'
import { Route as OwnerManagersRouteImport } from './routes/owner.managers'
import { Route as OwnerFormsRouteImport } from './routes/owner.forms'
import { Route as OwnerDriveLinksRouteImport } from './routes/owner.drive-links'
import { Route as OwnerBusinessConsultantsRouteImport } from './routes/owner.business-consultants'
import { Route as ManagerTasksRouteImport } from './routes/manager.tasks'
import { Route as ManagerSitesRouteImport } from './routes/manager.sites'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerPerformanceRouteImport } from './routes/manager.performance'
import { Route as ManagerDriveLinksRouteImport } from './routes/manager.drive-links'
import { Route as ManagerBusinessConsultantsRouteImport } from './routes/manager.business-consultants'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessConsultantRoute = BusinessConsultantRouteImport.update({
  id: '/business-consultant',
  path: '/business-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const OwnerTasksRoute = OwnerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSitesRoute = OwnerSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPerformanceRoute = OwnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerManagersRoute = OwnerManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerFormsRoute = OwnerFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDriveLinksRoute = OwnerDriveLinksRouteImport.update({
  id: '/drive-links',
  path: '/drive-links',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBusinessConsultantsRoute =
  OwnerBusinessConsultantsRouteImport.update({
    id: '/business-consultants',
    path: '/business-consultants',
    getParentRoute: () => OwnerRoute,
  } as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSitesRoute = ManagerSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPerformanceRoute = ManagerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerDriveLinksRoute = ManagerDriveLinksRouteImport.update({
  id: '/drive-links',
  path: '/drive-links',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBusinessConsultantsRoute =
  ManagerBusinessConsultantsRouteImport.update({
    id: '/business-consultants',
    path: '/business-consultants',
    getParentRoute: () => ManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager': typeof ManagerRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/owner/business-consultants': typeof OwnerBusinessConsultantsRoute
  '/owner/drive-links': typeof OwnerDriveLinksRoute
  '/owner/forms': typeof OwnerFormsRoute
  '/owner/managers': typeof OwnerManagersRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/sites': typeof OwnerSitesRoute
  '/owner/tasks': typeof OwnerTasksRoute
  '/manager/': typeof ManagerIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/owner/business-consultants': typeof OwnerBusinessConsultantsRoute
  '/owner/drive-links': typeof OwnerDriveLinksRoute
  '/owner/forms': typeof OwnerFormsRoute
  '/owner/managers': typeof OwnerManagersRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/sites': typeof OwnerSitesRoute
  '/owner/tasks': typeof OwnerTasksRoute
  '/manager': typeof ManagerIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/business-consultant': typeof BusinessConsultantRoute
  '/manager': typeof ManagerRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/manager/business-consultants': typeof ManagerBusinessConsultantsRoute
  '/manager/drive-links': typeof ManagerDriveLinksRoute
  '/manager/performance': typeof ManagerPerformanceRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/sites': typeof ManagerSitesRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/owner/business-consultants': typeof OwnerBusinessConsultantsRoute
  '/owner/drive-links': typeof OwnerDriveLinksRoute
  '/owner/forms': typeof OwnerFormsRoute
  '/owner/managers': typeof OwnerManagersRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/sites': typeof OwnerSitesRoute
  '/owner/tasks': typeof OwnerTasksRoute
  '/manager/': typeof ManagerIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager'
    | '/owner'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/owner/business-consultants'
    | '/owner/drive-links'
    | '/owner/forms'
    | '/owner/managers'
    | '/owner/performance'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/sites'
    | '/owner/tasks'
    | '/manager/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/owner/business-consultants'
    | '/owner/drive-links'
    | '/owner/forms'
    | '/owner/managers'
    | '/owner/performance'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/sites'
    | '/owner/tasks'
    | '/manager'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/business-consultant'
    | '/manager'
    | '/owner'
    | '/manager/business-consultants'
    | '/manager/drive-links'
    | '/manager/performance'
    | '/manager/reports'
    | '/manager/sites'
    | '/manager/tasks'
    | '/owner/business-consultants'
    | '/owner/drive-links'
    | '/owner/forms'
    | '/owner/managers'
    | '/owner/performance'
    | '/owner/reports'
    | '/owner/settings'
    | '/owner/sites'
    | '/owner/tasks'
    | '/manager/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BusinessConsultantRoute: typeof BusinessConsultantRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-consultant': {
      id: '/business-consultant'
      path: '/business-consultant'
      fullPath: '/business-consultant'
      preLoaderRoute: typeof BusinessConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/owner/tasks': {
      id: '/owner/tasks'
      path: '/tasks'
      fullPath: '/owner/tasks'
      preLoaderRoute: typeof OwnerTasksRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/sites': {
      id: '/owner/sites'
      path: '/sites'
      fullPath: '/owner/sites'
      preLoaderRoute: typeof OwnerSitesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/performance': {
      id: '/owner/performance'
      path: '/performance'
      fullPath: '/owner/performance'
      preLoaderRoute: typeof OwnerPerformanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/managers': {
      id: '/owner/managers'
      path: '/managers'
      fullPath: '/owner/managers'
      preLoaderRoute: typeof OwnerManagersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/forms': {
      id: '/owner/forms'
      path: '/forms'
      fullPath: '/owner/forms'
      preLoaderRoute: typeof OwnerFormsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/drive-links': {
      id: '/owner/drive-links'
      path: '/drive-links'
      fullPath: '/owner/drive-links'
      preLoaderRoute: typeof OwnerDriveLinksRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/business-consultants': {
      id: '/owner/business-consultants'
      path: '/business-consultants'
      fullPath: '/owner/business-consultants'
      preLoaderRoute: typeof OwnerBusinessConsultantsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/sites': {
      id: '/manager/sites'
      path: '/sites'
      fullPath: '/manager/sites'
      preLoaderRoute: typeof ManagerSitesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/performance': {
      id: '/manager/performance'
      path: '/performance'
      fullPath: '/manager/performance'
      preLoaderRoute: typeof ManagerPerformanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/drive-links': {
      id: '/manager/drive-links'
      path: '/drive-links'
      fullPath: '/manager/drive-links'
      preLoaderRoute: typeof ManagerDriveLinksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/business-consultants': {
      id: '/manager/business-consultants'
      path: '/business-consultants'
      fullPath: '/manager/business-consultants'
      preLoaderRoute: typeof ManagerBusinessConsultantsRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface ManagerRouteChildren {
  ManagerBusinessConsultantsRoute: typeof ManagerBusinessConsultantsRoute
  ManagerDriveLinksRoute: typeof ManagerDriveLinksRoute
  ManagerPerformanceRoute: typeof ManagerPerformanceRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSitesRoute: typeof ManagerSitesRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBusinessConsultantsRoute: ManagerBusinessConsultantsRoute,
  ManagerDriveLinksRoute: ManagerDriveLinksRoute,
  ManagerPerformanceRoute: ManagerPerformanceRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSitesRoute: ManagerSitesRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface OwnerRouteChildren {
  OwnerBusinessConsultantsRoute: typeof OwnerBusinessConsultantsRoute
  OwnerDriveLinksRoute: typeof OwnerDriveLinksRoute
  OwnerFormsRoute: typeof OwnerFormsRoute
  OwnerManagersRoute: typeof OwnerManagersRoute
  OwnerPerformanceRoute: typeof OwnerPerformanceRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerSitesRoute: typeof OwnerSitesRoute
  OwnerTasksRoute: typeof OwnerTasksRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerBusinessConsultantsRoute: OwnerBusinessConsultantsRoute,
  OwnerDriveLinksRoute: OwnerDriveLinksRoute,
  OwnerFormsRoute: OwnerFormsRoute,
  OwnerManagersRoute: OwnerManagersRoute,
  OwnerPerformanceRoute: OwnerPerformanceRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerSitesRoute: OwnerSitesRoute,
  OwnerTasksRoute: OwnerTasksRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BusinessConsultantRoute: BusinessConsultantRoute,
  ManagerRoute: ManagerRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
