// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.
// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.

// supabase/functions/_shared/attendance.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.0";

// supabase/functions/_shared/attendance-mqtt.ts
var encoder = new TextEncoder();
var decoder = new TextDecoder("utf-8", { fatal: true });
function concat(...parts) {
  const output = new Uint8Array(parts.reduce((sum, p) => sum + p.length, 0));
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
}
function word(value) {
  return Uint8Array.of(value >> 8, value & 255);
}
function text(value) {
  const bytes = encoder.encode(value);
  if (bytes.length > 65535 || value.includes("\0")) throw new Error("Invalid MQTT string");
  return concat(word(bytes.length), bytes);
}
function packet(header, body) {
  if (body.length > 65536) throw new Error("MQTT packet too large");
  let length = body.length;
  const encoded = [];
  do {
    let digit = length % 128;
    length = Math.floor(length / 128);
    if (length) digit |= 128;
    encoded.push(digit);
  } while (length);
  return concat(Uint8Array.of(header, ...encoded), body);
}
function validTopic(value) {
  if (typeof value !== "string" || !value || value.length > 256 || /[+#\0]/.test(value))
    throw new Error("Exact MQTT topic required");
}
function field(object, path) {
  return path.split(".").reduce(
    (value, key) => value && typeof value === "object" ? Reflect.get(value, key) : void 0,
    object
  );
}
function renderMqttEnrollment(template, command, deviceId) {
  const values = {
    command_id: command.id,
    device_id: deviceId,
    name: command.name,
    department: command.department,
    enroll_id: command.enroll_id
  };
  const visit = (value, depth = 0) => {
    if (depth > 16) throw new Error("Enrollment template too deep");
    if (Array.isArray(value)) return value.map((v) => visit(v, depth + 1));
    if (value && typeof value === "object")
      return Object.fromEntries(
        Object.entries(value).map(([key, v]) => [key, visit(v, depth + 1)])
      );
    if (typeof value === "string" && /^\{\{[a-z_]+\}\}$/.test(value)) {
      const key = value.slice(2, -2);
      if (key === "enroll_id_number") {
        if (!/^\d+$/.test(command.enroll_id) || !Number.isSafeInteger(Number(command.enroll_id)))
          throw new Error("Numeric enroll ID required");
        return Number(command.enroll_id);
      }
      if (!(key in values)) throw new Error("Unknown template placeholder");
      return values[key];
    }
    return value;
  };
  if (!template || typeof template !== "object" || Array.isArray(template))
    throw new Error("Enrollment template must be a JSON object");
  return visit(template);
}
function mqttConfig(get) {
  const names = [
    "ATTENDANCE_MQTT_HOST",
    "ATTENDANCE_MQTT_PORT",
    "ATTENDANCE_MQTT_TLS",
    "ATTENDANCE_MQTT_USERNAME",
    "ATTENDANCE_MQTT_PASSWORD",
    "ATTENDANCE_MQTT_ENROLL_TEMPLATE",
    "ATTENDANCE_COMMAND_TOPIC",
    "ATTENDANCE_DEVICE_ID"
  ];
  if (names.some((name) => !get(name))) return null;
  const port = Number(get("ATTENDANCE_MQTT_PORT"));
  const tls = get("ATTENDANCE_MQTT_TLS");
  if (!Number.isInteger(port) || port < 1 || port > 65535 || !["true", "false"].includes(tls))
    throw new Error("Invalid MQTT connection configuration");
  const topic = get("ATTENDANCE_COMMAND_TOPIC");
  validTopic(topic);
  const template = JSON.parse(get("ATTENDANCE_MQTT_ENROLL_TEMPLATE"));
  const ack = get("ATTENDANCE_MQTT_ACK_RULES") ? JSON.parse(get("ATTENDANCE_MQTT_ACK_RULES")) : void 0;
  if (ack) {
    validTopic(ack.topic);
    for (const key of [
      "kind_path",
      "command_id_path",
      "enroll_id_path",
      "serial_path",
      "success_path"
    ]) {
      if (typeof ack[key] !== "string" || !/^\w+(?:\.\w+)*$/.test(ack[key]))
        throw new Error("Invalid acknowledgment field mapping");
    }
    if (ack.kind_value === void 0 || ack.success_value === void 0 || ack.failure_value === void 0 || JSON.stringify(ack.success_value) === JSON.stringify(ack.failure_value))
      throw new Error("Explicit acknowledgment values required");
    if (!JSON.stringify(template).includes("{{command_id}}"))
      throw new Error("Device acknowledgments require command ID correlation");
  }
  const config = {
    host: get("ATTENDANCE_MQTT_HOST"),
    port,
    tls: tls === "true",
    username: get("ATTENDANCE_MQTT_USERNAME"),
    password: get("ATTENDANCE_MQTT_PASSWORD"),
    deviceId: get("ATTENDANCE_DEVICE_ID"),
    topic,
    template,
    ack,
    timeoutMs: 1e4
  };
  renderMqttEnrollment(
    template,
    { id: "validation", name: "validation", department: "software", enroll_id: "1" },
    config.deviceId
  );
  return config;
}
async function publishMqtt(config, command, connect) {
  let connection;
  let closed = false;
  let sending = false;
  let brokerAccepted = false;
  let ack = null;
  const deadline = Date.now() + config.timeoutMs;
  async function timed(promise) {
    const remaining = deadline - Date.now();
    if (remaining <= 0) {
      void promise.catch(() => {
      });
      throw new Error("MQTT timeout");
    }
    let timer;
    try {
      return await Promise.race([
        promise,
        new Promise((_, reject) => {
          timer = setTimeout(() => reject(new Error("MQTT timeout")), remaining);
        })
      ]);
    } finally {
      if (timer) clearTimeout(timer);
    }
  }
  async function write(bytes) {
    let offset = 0;
    while (offset < bytes.length) {
      const n = await timed(connection.write(bytes.subarray(offset)));
      if (n <= 0) throw new Error("MQTT write closed");
      offset += n;
    }
  }
  async function readExact(count) {
    const bytes = new Uint8Array(count);
    let offset = 0;
    while (offset < count) {
      const n = await timed(connection.read(bytes.subarray(offset)));
      if (!n) throw new Error("MQTT connection closed");
      offset += n;
    }
    return bytes;
  }
  async function readPacket() {
    const header = (await readExact(1))[0];
    let size = 0;
    let factor = 1;
    for (let i = 0; i < 4; i++) {
      const digit = (await readExact(1))[0];
      size += (digit & 127) * factor;
      if (size > 65536) throw new Error("MQTT response too large");
      if (!(digit & 128)) return { header, bytes: await readExact(size) };
      factor *= 128;
    }
    throw new Error("Malformed MQTT packet");
  }
  async function acceptReply(reply) {
    if (reply.header >> 4 !== 3) return;
    const bytes = reply.bytes;
    const qos = reply.header >> 1 & 3;
    if (bytes.length < 2 || qos > 1) throw new Error("Unsupported MQTT reply");
    const length = bytes[0] << 8 | bytes[1];
    let offset = 2 + length;
    if (offset + (qos === 1 ? 2 : 0) > bytes.length) throw new Error("Malformed MQTT reply");
    const topic = decoder.decode(bytes.subarray(2, offset));
    if (qos === 1) {
      await write(packet(64, bytes.subarray(offset, offset + 2)));
      offset += 2;
    }
    if (!config.ack || topic !== config.ack.topic || reply.header & 1) return;
    let data;
    try {
      data = JSON.parse(decoder.decode(bytes.subarray(offset)));
    } catch {
      return;
    }
    const rules = config.ack;
    if (field(data, rules.kind_path) !== rules.kind_value || field(data, rules.command_id_path) !== command.id || String(field(data, rules.enroll_id_path)) !== command.enroll_id || field(data, rules.serial_path) !== config.deviceId)
      return;
    const result = field(data, rules.success_path);
    if (result === rules.success_value) ack = true;
    else if (result === rules.failure_value) ack = false;
  }
  try {
    const payload = encoder.encode(
      JSON.stringify(renderMqttEnrollment(config.template, command, config.deviceId))
    );
    const opening = connect(config).then((conn) => {
      if (closed) conn.close();
      return conn;
    });
    connection = await timed(opening);
    const clientId = `att-${crypto.randomUUID().replaceAll("-", "").slice(0, 19)}`;
    await write(
      packet(
        16,
        concat(
          text("MQTT"),
          Uint8Array.of(4, 194),
          word(30),
          text(clientId),
          text(config.username),
          text(config.password)
        )
      )
    );
    const connack = await readPacket();
    if (connack.header !== 32 || connack.bytes.length !== 2 || connack.bytes[0] !== 0 || connack.bytes[1] !== 0)
      throw new Error("MQTT broker rejected connection");
    if (config.ack) {
      await write(packet(130, concat(word(1), text(config.ack.topic), Uint8Array.of(0))));
      while (true) {
        const reply = await readPacket();
        if (reply.header === 144) {
          if (reply.bytes.length !== 3 || reply.bytes[0] !== 0 || reply.bytes[1] !== 1 || reply.bytes[2] !== 0)
            throw new Error("MQTT subscription rejected");
          break;
        }
        if (reply.header >> 4 === 3 && (reply.header >> 1 & 3) === 1) {
          const n = reply.bytes[0] << 8 | reply.bytes[1];
          await write(packet(64, reply.bytes.subarray(2 + n, 4 + n)));
        }
      }
    }
    sending = true;
    await write(packet(50, concat(text(config.topic), word(2), payload)));
    while (true) {
      const reply = await readPacket();
      if (reply.header === 64 && reply.bytes.length === 2 && reply.bytes[0] === 0 && reply.bytes[1] === 2)
        brokerAccepted = true;
      else await acceptReply(reply);
      if (brokerAccepted && (!config.ack || ack !== null)) return { outcome: "published", ack };
    }
  } catch {
    return {
      outcome: brokerAccepted || ack !== null ? "published" : sending ? "uncertain" : "not_sent",
      ack
    };
  } finally {
    closed = true;
    try {
      connection?.close();
    } catch {
    }
  }
}

// supabase/functions/_shared/attendance.ts
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store"
};
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function env(name) {
  const value = Deno.env.get(name);
  if (!value) throw new HttpError(503, `Attendance configuration missing: ${name}`);
  return value;
}
function adminClient() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function json(body, status = 200) {
  return Response.json(body, { status, headers: cors });
}
function serve(handler) {
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json({ error: "POST required" }, 405);
    try {
      return await handler(req);
    } catch (error) {
      const status = error instanceof HttpError ? error.status : 400;
      return json(
        { error: error instanceof Error ? error.message : "Attendance request failed" },
        status
      );
    }
  });
}
async function secret(req, name) {
  const expected = env(name);
  const given = req.headers.get("x-attendance-secret") || "";
  const hash = async (text2) => new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text2)));
  const [a, b] = await Promise.all([hash(expected), hash(given)]);
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a[i] ^ b[i];
  if (mismatch || !given) throw new HttpError(401, "Unauthorized webhook");
}
function checked(result) {
  if (result.error) throw new HttpError(400, result.error.message);
  return result.data;
}
async function publishPending(admin, employee) {
  if (Deno.env.get("ATTENDANCE_PUBLISH_MODE") === "mqtt") {
    const config = mqttConfig((name) => Deno.env.get(name));
    if (!config) return { configured: false, sent: 0 };
    const commands2 = checked(
      await admin.rpc("attendance_claim_commands", { _employee: employee || null })
    );
    let sent2 = 0;
    for (const command of commands2) {
      const result = await publishMqtt(
        config,
        command,
        (connection) => connection.tls ? Deno.connectTls({ hostname: connection.host, port: connection.port }) : Deno.connect({ hostname: connection.host, port: connection.port, transport: "tcp" })
      );
      checked(
        await admin.rpc("attendance_mqtt_finish_command", {
          _id: command.id,
          _lease: command.lease_token,
          _outcome: result.outcome,
          _ack: result.ack
        })
      );
      if (result.outcome === "published") sent2++;
    }
    return { configured: true, sent: sent2 };
  }
  const endpoint = Deno.env.get("ATTENDANCE_PUBLISH_URL");
  const token = Deno.env.get("ATTENDANCE_PUBLISH_SECRET");
  const topic = Deno.env.get("ATTENDANCE_COMMAND_TOPIC");
  const device = Deno.env.get("ATTENDANCE_DEVICE_ID");
  if (!endpoint || !token || !topic || !device) return { configured: false, sent: 0 };
  if (new URL(endpoint).protocol !== "https:")
    throw new HttpError(503, "Publishing endpoint must use HTTPS");
  const commands = checked(
    await admin.rpc("attendance_claim_commands", { _employee: employee || null })
  );
  let sent = 0;
  for (const command of commands) {
    let ok = false;
    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-attendance-secret": token },
        body: JSON.stringify({
          command_id: command.id,
          device_id: device,
          topic,
          operation: "enroll",
          employee: {
            name: command.name,
            department: command.department,
            enroll_id: command.enroll_id
          }
        }),
        signal: AbortSignal.timeout(1e4),
        redirect: "error"
      });
      ok = response.ok;
      await response.body?.cancel();
    } catch {
      ok = false;
    }
    checked(
      await admin.rpc("attendance_finish_command", {
        _id: command.id,
        _lease: command.lease_token,
        _sent: ok
      })
    );
    if (ok) sent++;
  }
  return { configured: true, sent };
}

// supabase/functions/attendance-command-retry/index.ts
serve(async (req) => {
  await secret(req, "ATTENDANCE_CRON_SECRET");
  return json(await publishPending(adminClient()));
});
