// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.
// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.

// supabase/functions/_shared/attendance.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.0";
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store"
};
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function env(name) {
  const value = Deno.env.get(name);
  if (!value) throw new HttpError(503, `Attendance configuration missing: ${name}`);
  return value;
}
function adminClient() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function json(body2, status = 200) {
  return Response.json(body2, { status, headers: cors });
}
function serve(handler) {
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json({ error: "POST required" }, 405);
    try {
      return await handler(req);
    } catch (error) {
      const status = error instanceof HttpError ? error.status : 400;
      return json(
        { error: error instanceof Error ? error.message : "Attendance request failed" },
        status
      );
    }
  });
}
async function body(req, max = 16384) {
  const reader = req.body?.getReader();
  if (!reader) throw new HttpError(400, "Request body required");
  const chunks = [];
  let size = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    size += value.length;
    if (size > max) {
      await reader.cancel();
      throw new HttpError(413, "Request too large");
    }
    chunks.push(value);
  }
  const bytes = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.length;
  }
  const result = JSON.parse(new TextDecoder().decode(bytes));
  if (!result || typeof result !== "object" || Array.isArray(result))
    throw new HttpError(400, "JSON object required");
  return result;
}
async function manager(req) {
  const token = req.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  if (!token) throw new HttpError(401, "Sign in required");
  const admin = adminClient();
  const { data, error } = await admin.auth.getUser(token);
  if (error || !data.user) throw new HttpError(401, "Invalid session");
  const role = await admin.from("user_roles").select("role").eq("user_id", data.user.id).eq("role", "supervisor").maybeSingle();
  if (role.error || !role.data) throw new HttpError(403, "Manager access required");
  const user = createClient(env("SUPABASE_URL"), env("SUPABASE_ANON_KEY"), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
  return { admin, user, userId: data.user.id };
}
function checked(result) {
  if (result.error) throw new HttpError(400, result.error.message);
  return result.data;
}

// supabase/functions/_shared/attendance-validation.ts
function requiredText(value, field, max = 128) {
  if (typeof value !== "string" || !value.trim() || value.trim().length > max)
    throw new Error(`Invalid ${field}`);
  return value.trim();
}
function uuid(value) {
  const text = requiredText(value, "id", 36);
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(text))
    throw new Error("Invalid id");
  return text;
}

// supabase/functions/attendance-photo-access/index.ts
serve(async (req) => {
  const { admin } = await manager(req);
  const input = await body(req);
  const photo = checked(
    await admin.from("attendance_photos").select("*").eq("event_id", uuid(input.event_id)).maybeSingle()
  );
  if (!photo || photo.status !== "available") throw new HttpError(404, "Photo unavailable");
  const remaining = Math.floor((Date.parse(photo.expires_at) - Date.now()) / 1e3);
  if (remaining < 1) throw new HttpError(410, "Photo expired after 24 hours");
  const seconds = Math.min(60, remaining - 1);
  if (seconds < 1) throw new HttpError(410, "Photo is expiring; access is closed");
  const url = checked(
    await admin.storage.from("attendance-photos").createSignedUrl(photo.storage_path, seconds)
  );
  if (!url?.signedUrl) throw new HttpError(503, "Photo access unavailable");
  const accessExpiresAt = Date.now() + seconds * 1e3;
  if (accessExpiresAt > Date.parse(photo.expires_at))
    throw new HttpError(410, "Photo is expiring; access is closed");
  return json({
    url: url.signedUrl,
    expires_at: new Date(accessExpiresAt).toISOString(),
    photo_expires_at: photo.expires_at
  });
});
