// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.
// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.

// supabase/functions/_shared/attendance.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.0";
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store"
};
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function env(name) {
  const value = Deno.env.get(name);
  if (!value) throw new HttpError(503, `Attendance configuration missing: ${name}`);
  return value;
}
function adminClient() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function json(body, status = 200) {
  return Response.json(body, { status, headers: cors });
}
function serve(handler) {
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json({ error: "POST required" }, 405);
    try {
      return await handler(req);
    } catch (error) {
      const status = error instanceof HttpError ? error.status : 400;
      return json(
        { error: error instanceof Error ? error.message : "Attendance request failed" },
        status
      );
    }
  });
}
async function secret(req, name) {
  const expected = env(name);
  const given = req.headers.get("x-attendance-secret") || "";
  const hash = async (text) => new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)));
  const [a, b] = await Promise.all([hash(expected), hash(given)]);
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a[i] ^ b[i];
  if (mismatch || !given) throw new HttpError(401, "Unauthorized webhook");
}
function checked(result) {
  if (result.error) throw new HttpError(400, result.error.message);
  return result.data;
}

// supabase/functions/attendance-photo-cleanup/index.ts
serve(async (req) => {
  await secret(req, "ATTENDANCE_CRON_SECRET");
  const admin = adminClient();
  const expired = checked(
    await admin.from("attendance_photos").select("*").lte("expires_at", (/* @__PURE__ */ new Date()).toISOString()).neq("status", "deleted").order("expires_at").limit(100)
  );
  let deleted = 0;
  let failed = 0;
  for (const photo of expired || []) {
    try {
      checked(await admin.storage.from("attendance-photos").remove([photo.storage_path]));
      checked(
        await admin.from("attendance_photos").update({ status: "deleted", deleted_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("event_id", photo.event_id)
      );
      deleted++;
    } catch {
      failed++;
    }
  }
  const files = checked(
    await admin.storage.from("attendance-photos").list("", { limit: 100, sortBy: { column: "created_at", order: "asc" } })
  );
  for (const file of files || []) {
    const meta = checked(
      await admin.from("attendance_photos").select("expires_at,status").eq("storage_path", file.name).maybeSingle()
    );
    if (meta && Date.parse(meta.expires_at) <= Date.now() || !meta && file.created_at && Date.parse(file.created_at) + 864e5 <= Date.now()) {
      const result = await admin.storage.from("attendance-photos").remove([file.name]);
      if (result.error) failed++;
    }
  }
  return json({ deleted, failed }, failed ? 503 : 200);
});
