// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.
// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.

// supabase/functions/_shared/attendance.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.0";
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store"
};
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function env(name) {
  const value = Deno.env.get(name);
  if (!value) throw new HttpError(503, `Attendance configuration missing: ${name}`);
  return value;
}
function adminClient() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function json(body2, status = 200) {
  return Response.json(body2, { status, headers: cors });
}
function serve(handler) {
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json({ error: "POST required" }, 405);
    try {
      return await handler(req);
    } catch (error) {
      const status = error instanceof HttpError ? error.status : 400;
      return json(
        { error: error instanceof Error ? error.message : "Attendance request failed" },
        status
      );
    }
  });
}
async function body(req, max = 16384) {
  const reader = req.body?.getReader();
  if (!reader) throw new HttpError(400, "Request body required");
  const chunks = [];
  let size = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    size += value.length;
    if (size > max) {
      await reader.cancel();
      throw new HttpError(413, "Request too large");
    }
    chunks.push(value);
  }
  const bytes = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.length;
  }
  const result = JSON.parse(new TextDecoder().decode(bytes));
  if (!result || typeof result !== "object" || Array.isArray(result))
    throw new HttpError(400, "JSON object required");
  return result;
}
function checked(result) {
  if (result.error) throw new HttpError(400, result.error.message);
  return result.data;
}

// supabase/functions/_shared/attendance-validation.ts
function requiredText(value, field, max = 128) {
  if (typeof value !== "string" || !value.trim() || value.trim().length > max)
    throw new Error(`Invalid ${field}`);
  return value.trim();
}
function dateOrNull(value) {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
  const date = /* @__PURE__ */ new Date(`${value}T00:00:00Z`);
  return Number.isFinite(date.getTime()) && date.toISOString().slice(0, 10) === value ? value : null;
}

// supabase/functions/attendance-leave-email/index.ts
serve(async (req) => {
  const timestamp = req.headers.get("x-attendance-timestamp") || "";
  if (!/^\d{10}$/.test(timestamp) || Math.abs(Date.now() / 1e3 - Number(timestamp)) > 300)
    throw new HttpError(401, "Expired email webhook");
  const input = await body(req, 12e3);
  const signature = req.headers.get("x-attendance-signature") || "";
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(env("ATTENDANCE_EMAIL_WEBHOOK_SECRET")),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["verify"]
  );
  if (!/^[0-9a-f]{64}$/i.test(signature)) throw new HttpError(401, "Invalid email signature");
  const bytes = Uint8Array.from(signature.match(/../g), (hex) => parseInt(hex, 16));
  const valid = await crypto.subtle.verify(
    "HMAC",
    key,
    bytes,
    new TextEncoder().encode(`${timestamp}.${JSON.stringify(input)}`)
  );
  if (!valid) throw new HttpError(401, "Invalid email signature");
  const sender = requiredText(input.sender, "sender", 254).toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(sender)) throw new Error("Invalid sender email");
  const request = checked(
    await adminClient().rpc("attendance_email_leave", {
      _message_id: requiredText(input.message_id, "message_id", 200),
      _sender: sender,
      _start: dateOrNull(input.start_date),
      _end: dateOrNull(input.end_date),
      _reason: requiredText(input.reason, "reason", 2e3)
    })
  );
  return json({ request_id: request, status: "received_for_review" });
});
