// Generated by supabase/scripts/build_attendance_dashboard.mjs. Edit the source function, then regenerate.
// Supabase Edge Function: keep gateway Verify JWT disabled; authorization is enforced inside this function.

// supabase/functions/_shared/attendance.ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.108.0";
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store"
};
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function env(name) {
  const value = Deno.env.get(name);
  if (!value) throw new HttpError(503, `Attendance configuration missing: ${name}`);
  return value;
}
function adminClient() {
  return createClient(env("SUPABASE_URL"), env("SUPABASE_SERVICE_ROLE_KEY"), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function json(body2, status = 200) {
  return Response.json(body2, { status, headers: cors });
}
function serve(handler) {
  Deno.serve(async (req) => {
    if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
    if (req.method !== "POST") return json({ error: "POST required" }, 405);
    try {
      return await handler(req);
    } catch (error) {
      const status = error instanceof HttpError ? error.status : 400;
      return json(
        { error: error instanceof Error ? error.message : "Attendance request failed" },
        status
      );
    }
  });
}
async function body(req, max = 16384) {
  const reader = req.body?.getReader();
  if (!reader) throw new HttpError(400, "Request body required");
  const chunks = [];
  let size = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    size += value.length;
    if (size > max) {
      await reader.cancel();
      throw new HttpError(413, "Request too large");
    }
    chunks.push(value);
  }
  const bytes = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.length;
  }
  const result = JSON.parse(new TextDecoder().decode(bytes));
  if (!result || typeof result !== "object" || Array.isArray(result))
    throw new HttpError(400, "JSON object required");
  return result;
}
async function secret(req, name) {
  const expected = env(name);
  const given = req.headers.get("x-attendance-secret") || "";
  const hash = async (text) => new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text)));
  const [a, b] = await Promise.all([hash(expected), hash(given)]);
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a[i] ^ b[i];
  if (mismatch || !given) throw new HttpError(401, "Unauthorized webhook");
}
function checked(result) {
  if (result.error) throw new HttpError(400, result.error.message);
  return result.data;
}

// supabase/functions/_shared/attendance-validation.ts
function requiredText(value, field, max = 128) {
  if (typeof value !== "string" || !value.trim() || value.trim().length > max)
    throw new Error(`Invalid ${field}`);
  return value.trim();
}
function isoTimestamp(value) {
  const text = requiredText(value, "scanned_at", 40);
  if (!dateOrNull(text.slice(0, 10))) throw new Error("Invalid scan date");
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(text) || !Number.isFinite(Date.parse(text)))
    throw new Error("scanned_at must include a timezone");
  return new Date(text).toISOString();
}
function dateOrNull(value) {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
  const date = /* @__PURE__ */ new Date(`${value}T00:00:00Z`);
  return Number.isFinite(date.getTime()) && date.toISOString().slice(0, 10) === value ? value : null;
}
function uuid(value) {
  const text = requiredText(value, "id", 36);
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(text))
    throw new Error("Invalid id");
  return text;
}
function photoBytes(base64, mime) {
  if (mime !== "image/jpeg" && mime !== "image/png")
    throw new Error("Only JPEG and PNG photos are accepted");
  const encoded = requiredText(base64, "photo_base64", 28e5);
  const raw = atob(encoded);
  if (!raw.length || raw.length > 2097152) throw new Error("Photo exceeds 2 MB");
  const bytes = Uint8Array.from(raw, (c) => c.charCodeAt(0));
  const jpeg = bytes[0] === 255 && bytes[1] === 216 && bytes[2] === 255;
  const png = [137, 80, 78, 71, 13, 10, 26, 10].every((b, i) => bytes[i] === b);
  if (mime === "image/jpeg" ? !jpeg : !png)
    throw new Error("Photo content does not match its MIME type");
  return { bytes, mime };
}

// supabase/functions/attendance-device-event/index.ts
serve(async (req) => {
  await secret(req, "ATTENDANCE_DEVICE_WEBHOOK_SECRET");
  const input = await body(req, 29e5);
  if (input.device_id !== env("ATTENDANCE_DEVICE_ID"))
    throw new HttpError(403, "Device not allowed");
  const allowed = env("ATTENDANCE_EVENT_TOPICS").split(",").map((t) => t.trim()).filter(Boolean);
  if (typeof input.topic !== "string" || !allowed.includes(input.topic))
    throw new HttpError(403, "Topic not allowed");
  const admin = adminClient();
  if (input.kind === "heartbeat") {
    const observed = Date.parse(isoTimestamp(input.observed_at));
    if (Math.abs(Date.now() - observed) > 6e4)
      throw new HttpError(400, "Fresh device heartbeat required");
    checked(await admin.rpc("attendance_heartbeat"));
    return json({ accepted: true });
  }
  if (input.kind === "enrollment_ack") {
    if (typeof input.success !== "boolean") throw new Error("Boolean success required");
    checked(
      await admin.rpc("attendance_ack_command", {
        _id: uuid(input.command_id),
        _enroll_id: requiredText(input.enroll_id, "enroll_id", 64),
        _success: input.success
      })
    );
    return json({ accepted: true });
  }
  if (input.kind !== "scan" || typeof input.recognized !== "boolean")
    throw new Error("A scan requires kind and boolean recognized");
  const event = checked(
    await admin.rpc("attendance_ingest_scan", {
      _event_id: requiredText(input.event_id, "event_id"),
      _enroll_id: requiredText(input.enroll_id, "enroll_id", 64),
      _scanned_at: isoTimestamp(input.scanned_at),
      _recognized: input.recognized
    })
  );
  if (event.state !== "valid" || !input.photo_base64 || Date.parse(event.expires_at) <= Date.now())
    return json({ ...event, photo: "not_stored" });
  try {
    const photo = photoBytes(input.photo_base64, input.photo_mime);
    const path = `${event.id}.${photo.mime === "image/jpeg" ? "jpg" : "png"}`;
    const existing = checked(
      await admin.from("attendance_photos").select("*").eq("event_id", event.id).maybeSingle()
    );
    if (existing?.status === "available") return json({ ...event, photo: "available" });
    if (existing?.status === "deleted") return json({ ...event, photo: "expired" });
    if (!existing)
      checked(
        await admin.from("attendance_photos").insert({ event_id: event.id, storage_path: path, expires_at: event.expires_at })
      );
    const target = existing?.storage_path || path;
    checked(
      await admin.storage.from("attendance-photos").upload(target, photo.bytes, { contentType: photo.mime, upsert: true, cacheControl: "0" })
    );
    if (Date.parse(event.expires_at) <= Date.now()) {
      checked(await admin.storage.from("attendance-photos").remove([target]));
      checked(
        await admin.from("attendance_photos").update({ status: "deleted", deleted_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("event_id", event.id)
      );
      return json({ ...event, photo: "expired" });
    }
    const updated = checked(
      await admin.from("attendance_photos").update({ status: "available" }).eq("event_id", event.id).neq("status", "deleted").select("event_id")
    );
    if (!updated?.length) checked(await admin.storage.from("attendance-photos").remove([target]));
    return json({ ...event, photo: updated?.length ? "available" : "expired" });
  } catch {
    return json({ ...event, photo: "retry_needed" }, 503);
  }
});
